### ISSUE TITLE
Docker it!

### ISSUE THREAD

**Issue by pandres95** [bhberson/pizzadash#10]
Other ideas? Dockerize it and enable to install to a Raspberry Pi and configure it using a web interface!

That'd be a whole new level of lazyness to get a pizza forever.

Please tell me how can I help you with this. Please :joy:

**Comment by JoeIaquinto** [comment]
I'm working on a fork of this project right now to aid with the setup of orders and buttons with a setup CLI. I will look into this and see if my team wants to go for it. Another choice could be to use the dash button to trigger an AWS Lambda function to place the order, which would be cool too.

**Comment by mynamebrody** [comment]
@pandres95 If you'd like to contribute, I'm more than willing to to CR. I'm excited to see what @JoeIaquinto puts together.

I also have another repo Drizly Dash in which I created a GIST to be triggered via AWS Lambda... https://gist.github.com/bhberson/ab99c5f53467b9b481c1
