### ISSUE TITLE
Error: Cannot find module '/Users/dave/node_modules/node-dash-button/bin/findbutton

### ISSUE THREAD

**Issue by Digipup1** [bhberson/pizzadash#17]
I've run the command `sudo node node_modules/node-dash-button/bin/findbutton` on two different computers and gotten the same error response. I apologize if this is a user error.

**Comment by JoeIaquinto** [comment]
Did you npm install? Are you running the command from the folder where you cloned pizzadash to? It's looking for a node_modules folder inside dave/ but it should be looking for it inside dave/pizzadash/ or whatever you named your folder where the node_modules would be downloaded after an npm install

**Comment by Digipup1** [comment]
Thanks! I've got it now.
