### ISSUE TITLE
After setup, app not communicating with Dominos

### ISSUE THREAD

**Issue by gyamada619** [bhberson/pizzadash#4]
I've set up your application as described, all dependencies are installed, and the app.js file has been modified with correct customer info. Yet it does not actually place the order when the button is pushed (although the console log says it does, and I don't receive any errors). If you have any idea why this might be, please help!

**Comment by RIAEvangelist** [comment]
I'll be testing this repo as soon as my Dash arrives too. Looking forward to some amazon style Pizza.

**Comment by mynamebrody** [comment]
I believe I may know the problem! I think it has to do with the dominos npm module. I had to manually install the latest version from their repo. They have some fixes in the master branch that are not in the version hosted on npm :/ (such as saving the phone number)

**Comment by gyamada619** [comment]
Thank you! I'll be giving that a try.
