### ISSUE TITLE
everything except pcap and socket watcher loads on OS X

### ISSUE THREAD

**Issue by anthonyseo** [bhberson/pizzadash#8]
13 errors generated.
make: **\* [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Optical/Users/anthonyseo/Downloads/pizzadash-master/node_modules/socketwatcher
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socketwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Optical/Users/anthonyseo/Downloads/pizzadash-master/npm-debug.log

**Comment by mynamebrody** [comment]
Is this when performing `npm install` ? If so what version of npm and node are you running?

**Comment by bhargavrpatel** [comment]
I personally have the same problem... npm@3.6.0 /usr/local/lib/node_modules/npm

**Comment by JoeIaquinto** [comment]
Same issue here on Raspian. Socketwatcher is broken.  https://gist.github.com/95bc07f5b2f2e5f3660593ca42d79b2c

**Comment by JoeIaquinto** [comment]
Looks like socketwatcher was using the legacy "node" command instead of nodejs. I solved it on ubuntu by installing nodejs-legacy that clears up those conflicts.

sudo apt-get install nodejs-legacy

**Comment by mynamebrody** [comment]
Glad you were able to get it resolved with that command. I'll update the Read Me
